### ISSUE TITLE
Library consumers need storm dependency?

### ISSUE THREAD

**Issue by u0xee** [yieldbot/marceline#22]
In order to successfully `(require 'marceline.storm.trident)` I needed a dependency on `storm-core` in my `project.clj`. This was challenging to troubleshoot.

I think I don't understand something about how project dependencies work or the intended workflow here. If the dependency is necessary, I'd like to note that in the README.

Let me know if I can help clarify or investigate.

**Comment by sorenmacbeth** [comment]
marceline does indeed require storm. The way this is handled in leiningen is my using a `:provided` profile as referenced here in the leiningen tutorial:

https://github.com/technomancy/leiningen/blob/master/doc/TUTORIAL.md#framework-uberjars

something like this:

```clojure
:profiles {:provided {:dependencies [[org.apache.storm/storm-core "1.0.1"]]}}
```
